---
apiVersion: v1
kind: Secret
metadata:
  name: dex-tls
  namespace: kube-system
type: Opaque
data:
  dex.crt: {{ salt.hashutil.base64_encodefile(pillar['ssl']['dex_crt']) | replace("\n", "") }} 
  dex.key: {{ salt.hashutil.base64_encodefile(pillar['ssl']['dex_key']) | replace("\n", "") }}
