---
apiVersion: v1
kind: Service
metadata:
  name: dex
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Dex"
spec:
  type: NodePort
  ports:
  - name: dex
    port: 5556
    protocol: TCP
    targetPort: https
    nodePort: {{ pillar['dex']['node_port'] }}
  selector:
    app: dex
